# Generated by Django 3.0.3 on 2021-04-28 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_signup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='signup',
        ),
    ]
