# Generated by Django 3.0.3 on 2021-04-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_signup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pdec',
        ),
        migrations.AddField(
            model_name='product',
            name='img1',
            field=models.ImageField(null=True, upload_to='img1'),
        ),
        migrations.AddField(
            model_name='product',
            name='img2',
            field=models.ImageField(null=True, upload_to='img2'),
        ),
    ]
