# Generated by Django 3.1 on 2021-05-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='reg',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='reg',
            name='phone',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
