# Generated by Django 3.1 on 2021-05-14 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210513_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('pincode', models.PositiveIntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.reg')),
            ],
        ),
    ]
